### ISSUE TITLE
Issue with ...

### ISSUE THREAD

**Issue by Killerbee47** [grilled-salmon/oldguns#37] opened 2022-10-14 03:06 UTC
**Describe the bug**
Players not in the immediate vincinity of a gun being fired, a cannon being fired, or rocket artillery being fired are kicked from the server.

**To Reproduce**
1. Go to a server/multiplayer world
2. maintain an approximately 100-200 block distance (out of render distance)
3. one person fires a weapon
4. other person should be kicked

**Expected behavior**
Nothing should happen when a gun is fired, and definitely should not disconnect players. 

**Screenshots**
![unknown-1](https://user-images.githubusercontent.com/115763883/195751813-081e7d41-39c8-47f5-9f58-2386df2a0317.png)
here is the kick message when you are disconnected after someone fires a gun from a distance

**Mod Version**
oldguns-1.19-3.6.2-34.

**Mod List**
```
oldguns-1.19-3.6.2-34.
guardvillagers-1.19-1.5.1
illagersweararmor-1.2.1
smallships-1.19-2.0.0


...
```

**Additional context**
Logs of the day that this bug was happening are attached. (The mod was removed from the server later)
If the error cannot be found within these logs, please contact me, there were like 50 logs made for 2022-10-11, this is the last one made for that day
[2022-10-11-9.log](https://github.com/zach2039/oldguns/files/9782119/2022-10-11-9.log)

**Comment by SirCatZ** [comment] 2022-12-25 04:40
copy pasta from another issue entry (but with the same problem, sry for the spam :/ ):

One of my friends fixed this issue.
If i understood it correctly the mod already includes the code to stop distant clients from trying to render the bullets (which crashes the client when this chunks aren't loaded).
The error in the code is that the distance is entered wrong (the Minecraft documentation includes a wrong statement, so its not the creators fault (can't remember exactly, but something like if the value is already squared or not)).

i'll include the edited version we used (and tested successfully). Maybe the creator of the mod can later include the fix in an official version.

[oldguns-MODIFIED.zip](https://github.com/zach2039/oldguns/files/10299431/oldguns-MODIFIED.zip)

**Comment by zach2039** [comment] 2022-12-31 18:14
duplicate of #29

**Closed as not planned by zach2039** 2022-12-31 18:14 UTC
Labels: bug
