### ISSUE TITLE
Client side crash when firing guns

### ISSUE THREAD

**Issue by SunjuhCeles** [grilled-salmon/oldguns#33] opened 2022-08-10 09:17 UTC
Client side crash when another player fires a gun 124 blocks away. Player firing the gun is not disconnected. This does not happen when the two players are next to each other

1. Fire any gun with another player on a server
2. Be at least 100 blocks away
3. See error

![oldgunserror](https://user-images.githubusercontent.com/110972236/183862758-dd382905-6513-4483-b92c-99d5dc195ea5.png)

Version
[eg. v1.19-3.6.2-34]

**Mod List**

![modlist](https://user-images.githubusercontent.com/110972236/183864258-55c00fd5-21cd-48c7-8bc1-5d939b4698b1.png)

Additional context
There is no crash log for the issue

**Comment by SirCatZ** [comment] 2022-12-25 04:34
One of my friends fixed this issue.
If i understood it correctly the mod already includes the code to stop distant clients from trying to render the bullets (which crashes the client when this chunks aren't loaded). 
The error in the code is that the distance is entered wrong (the Minecraft documentation includes a wrong statement, so its not the creators fault (can't remember exactly, but something like if the value is already squared or not)).

i'll include the edited version we used (and tested successfully). Maybe the creator of the mod can later include the fix in an official version.

[oldguns-MODIFIED.zip](https://github.com/zach2039/oldguns/files/10299431/oldguns-MODIFIED.zip)

**Comment by zach2039** [comment] 2022-12-31 18:13
duplicate of #29

**Comment by zach2039** [comment] 2022-12-31 18:13
duplicate of #29

**Closed as not planned by zach2039** 2022-12-31 18:13 UTC
Labels: bug, MC-1.19.x
